// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

/**
 * Protobuf type {@code auth.proto.AuthResponse}
 */
public  final class AuthResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:auth.proto.AuthResponse)
    AuthResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuthResponse.newBuilder() to construct.
  private AuthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthResponse() {
    tokenValid_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AuthResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            sirup.service.auth.rpc.proto.ErrorRpc.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(sirup.service.auth.rpc.proto.ErrorRpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            tokenValid_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_AuthResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_AuthResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sirup.service.auth.rpc.proto.AuthResponse.class, sirup.service.auth.rpc.proto.AuthResponse.Builder.class);
  }

  public static final int ERROR_FIELD_NUMBER = 1;
  private sirup.service.auth.rpc.proto.ErrorRpc error_;
  /**
   * <code>.auth.proto.ErrorRpc error = 1;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.auth.proto.ErrorRpc error = 1;</code>
   */
  public sirup.service.auth.rpc.proto.ErrorRpc getError() {
    return error_ == null ? sirup.service.auth.rpc.proto.ErrorRpc.getDefaultInstance() : error_;
  }
  /**
   * <code>.auth.proto.ErrorRpc error = 1;</code>
   */
  public sirup.service.auth.rpc.proto.ErrorRpcOrBuilder getErrorOrBuilder() {
    return getError();
  }

  public static final int TOKENVALID_FIELD_NUMBER = 2;
  private boolean tokenValid_;
  /**
   * <code>bool tokenValid = 2;</code>
   */
  public boolean getTokenValid() {
    return tokenValid_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (error_ != null) {
      output.writeMessage(1, getError());
    }
    if (tokenValid_ != false) {
      output.writeBool(2, tokenValid_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    if (tokenValid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, tokenValid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sirup.service.auth.rpc.proto.AuthResponse)) {
      return super.equals(obj);
    }
    sirup.service.auth.rpc.proto.AuthResponse other = (sirup.service.auth.rpc.proto.AuthResponse) obj;

    boolean result = true;
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    result = result && (getTokenValid()
        == other.getTokenValid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (37 * hash) + TOKENVALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTokenValid());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.auth.rpc.proto.AuthResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sirup.service.auth.rpc.proto.AuthResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code auth.proto.AuthResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:auth.proto.AuthResponse)
      sirup.service.auth.rpc.proto.AuthResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_AuthResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_AuthResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sirup.service.auth.rpc.proto.AuthResponse.class, sirup.service.auth.rpc.proto.AuthResponse.Builder.class);
    }

    // Construct using sirup.service.auth.rpc.proto.AuthResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      tokenValid_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_AuthResponse_descriptor;
    }

    @java.lang.Override
    public sirup.service.auth.rpc.proto.AuthResponse getDefaultInstanceForType() {
      return sirup.service.auth.rpc.proto.AuthResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sirup.service.auth.rpc.proto.AuthResponse build() {
      sirup.service.auth.rpc.proto.AuthResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sirup.service.auth.rpc.proto.AuthResponse buildPartial() {
      sirup.service.auth.rpc.proto.AuthResponse result = new sirup.service.auth.rpc.proto.AuthResponse(this);
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      result.tokenValid_ = tokenValid_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sirup.service.auth.rpc.proto.AuthResponse) {
        return mergeFrom((sirup.service.auth.rpc.proto.AuthResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sirup.service.auth.rpc.proto.AuthResponse other) {
      if (other == sirup.service.auth.rpc.proto.AuthResponse.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (other.getTokenValid() != false) {
        setTokenValid(other.getTokenValid());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sirup.service.auth.rpc.proto.AuthResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sirup.service.auth.rpc.proto.AuthResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private sirup.service.auth.rpc.proto.ErrorRpc error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sirup.service.auth.rpc.proto.ErrorRpc, sirup.service.auth.rpc.proto.ErrorRpc.Builder, sirup.service.auth.rpc.proto.ErrorRpcOrBuilder> errorBuilder_;
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    public sirup.service.auth.rpc.proto.ErrorRpc getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? sirup.service.auth.rpc.proto.ErrorRpc.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    public Builder setError(sirup.service.auth.rpc.proto.ErrorRpc value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    public Builder setError(
        sirup.service.auth.rpc.proto.ErrorRpc.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    public Builder mergeError(sirup.service.auth.rpc.proto.ErrorRpc value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            sirup.service.auth.rpc.proto.ErrorRpc.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    public sirup.service.auth.rpc.proto.ErrorRpc.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    public sirup.service.auth.rpc.proto.ErrorRpcOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            sirup.service.auth.rpc.proto.ErrorRpc.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.auth.proto.ErrorRpc error = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sirup.service.auth.rpc.proto.ErrorRpc, sirup.service.auth.rpc.proto.ErrorRpc.Builder, sirup.service.auth.rpc.proto.ErrorRpcOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sirup.service.auth.rpc.proto.ErrorRpc, sirup.service.auth.rpc.proto.ErrorRpc.Builder, sirup.service.auth.rpc.proto.ErrorRpcOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private boolean tokenValid_ ;
    /**
     * <code>bool tokenValid = 2;</code>
     */
    public boolean getTokenValid() {
      return tokenValid_;
    }
    /**
     * <code>bool tokenValid = 2;</code>
     */
    public Builder setTokenValid(boolean value) {
      
      tokenValid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool tokenValid = 2;</code>
     */
    public Builder clearTokenValid() {
      
      tokenValid_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:auth.proto.AuthResponse)
  }

  // @@protoc_insertion_point(class_scope:auth.proto.AuthResponse)
  private static final sirup.service.auth.rpc.proto.AuthResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sirup.service.auth.rpc.proto.AuthResponse();
  }

  public static sirup.service.auth.rpc.proto.AuthResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthResponse>
      PARSER = new com.google.protobuf.AbstractParser<AuthResponse>() {
    @java.lang.Override
    public AuthResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AuthResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AuthResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sirup.service.auth.rpc.proto.AuthResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

