// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_proto_TokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_proto_TokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_proto_TokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_proto_TokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_proto_AuthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_proto_AuthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_proto_AuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_proto_AuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_proto_CredentialsRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_proto_CredentialsRpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_proto_ErrorRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_proto_ErrorRpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020sirup_auth.proto\022\nauth.proto\"?\n\014TokenR" +
      "equest\022/\n\013credentials\030\001 \001(\0132\032.auth.proto" +
      ".CredentialsRpc\"C\n\rTokenResponse\022#\n\005erro" +
      "r\030\001 \001(\0132\024.auth.proto.ErrorRpc\022\r\n\005token\030\002" +
      " \001(\t\"P\n\013AuthRequest\022\r\n\005token\030\001 \001(\t\0222\n\016Cr" +
      "edentialsRpc\030\002 \001(\0132\032.auth.proto.Credenti" +
      "alsRpc\"G\n\014AuthResponse\022#\n\005error\030\001 \001(\0132\024." +
      "auth.proto.ErrorRpc\022\022\n\ntokenValid\030\002 \001(\010\"" +
      " \n\016CredentialsRpc\022\016\n\006userID\030\001 \001(\t\"0\n\010Err" +
      "orRpc\022\016\n\006status\030\001 \001(\005\022\024\n\014errorMessage\030\002 " +
      "\001(\t2\210\001\n\tSirupAuth\022>\n\005token\022\030.auth.proto." +
      "TokenRequest\032\031.auth.proto.TokenResponse\"" +
      "\000\022;\n\004auth\022\027.auth.proto.AuthRequest\032\030.aut" +
      "h.proto.AuthResponse\"\000B,\n\034sirup.service." +
      "auth.rpc.protoB\004AuthP\001\242\002\003SASb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_auth_proto_TokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_proto_TokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_proto_TokenRequest_descriptor,
        new java.lang.String[] { "Credentials", });
    internal_static_auth_proto_TokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_proto_TokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_proto_TokenResponse_descriptor,
        new java.lang.String[] { "Error", "Token", });
    internal_static_auth_proto_AuthRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_auth_proto_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_proto_AuthRequest_descriptor,
        new java.lang.String[] { "Token", "CredentialsRpc", });
    internal_static_auth_proto_AuthResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_auth_proto_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_proto_AuthResponse_descriptor,
        new java.lang.String[] { "Error", "TokenValid", });
    internal_static_auth_proto_CredentialsRpc_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_auth_proto_CredentialsRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_proto_CredentialsRpc_descriptor,
        new java.lang.String[] { "UserID", });
    internal_static_auth_proto_ErrorRpc_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_auth_proto_ErrorRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_proto_ErrorRpc_descriptor,
        new java.lang.String[] { "Status", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
