// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

public interface AuthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.v2.AuthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.auth.v2.ErrorRpc error = 1;</code>
   */
  boolean hasError();
  /**
   * <code>.auth.v2.ErrorRpc error = 1;</code>
   */
  sirup.service.auth.rpc.proto.ErrorRpc getError();
  /**
   * <code>.auth.v2.ErrorRpc error = 1;</code>
   */
  sirup.service.auth.rpc.proto.ErrorRpcOrBuilder getErrorOrBuilder();

  /**
   * <code>bool token_valid = 2;</code>
   */
  boolean getTokenValid();
}
