// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

public interface AuthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.proto.AuthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool tokenValid = 1;</code>
   */
  boolean getTokenValid();
}
