// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

public interface CredentialsRpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.proto.CredentialsRpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userID = 1;</code>
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIDBytes();
}
