// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

public interface HealthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.v4.HealthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 health_code = 1;</code>
   */
  int getHealthCode();
}
