// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

public interface HealthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.v2.HealthRequest)
    com.google.protobuf.MessageOrBuilder {
}
