// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

public interface ServiceTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.v4.ServiceTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.auth.v4.CredentialsRpc admin_credentials = 1;</code>
   */
  boolean hasAdminCredentials();
  /**
   * <code>.auth.v4.CredentialsRpc admin_credentials = 1;</code>
   */
  sirup.service.auth.rpc.proto.CredentialsRpc getAdminCredentials();
  /**
   * <code>.auth.v4.CredentialsRpc admin_credentials = 1;</code>
   */
  sirup.service.auth.rpc.proto.CredentialsRpcOrBuilder getAdminCredentialsOrBuilder();

  /**
   * <code>string admin_token = 2;</code>
   */
  java.lang.String getAdminToken();
  /**
   * <code>string admin_token = 2;</code>
   */
  com.google.protobuf.ByteString
      getAdminTokenBytes();

  /**
   * <code>.auth.v4.CredentialsRpc service_credentials = 3;</code>
   */
  boolean hasServiceCredentials();
  /**
   * <code>.auth.v4.CredentialsRpc service_credentials = 3;</code>
   */
  sirup.service.auth.rpc.proto.CredentialsRpc getServiceCredentials();
  /**
   * <code>.auth.v4.CredentialsRpc service_credentials = 3;</code>
   */
  sirup.service.auth.rpc.proto.CredentialsRpcOrBuilder getServiceCredentialsOrBuilder();
}
