// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

/**
 * Protobuf type {@code auth.proto.TokenRequest}
 */
public  final class TokenRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:auth.proto.TokenRequest)
    TokenRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TokenRequest.newBuilder() to construct.
  private TokenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TokenRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TokenRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            sirup.service.auth.rpc.proto.CredentialsRpc.Builder subBuilder = null;
            if (credentials_ != null) {
              subBuilder = credentials_.toBuilder();
            }
            credentials_ = input.readMessage(sirup.service.auth.rpc.proto.CredentialsRpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(credentials_);
              credentials_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_TokenRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_TokenRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sirup.service.auth.rpc.proto.TokenRequest.class, sirup.service.auth.rpc.proto.TokenRequest.Builder.class);
  }

  public static final int CREDENTIALS_FIELD_NUMBER = 1;
  private sirup.service.auth.rpc.proto.CredentialsRpc credentials_;
  /**
   * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
   */
  public boolean hasCredentials() {
    return credentials_ != null;
  }
  /**
   * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
   */
  public sirup.service.auth.rpc.proto.CredentialsRpc getCredentials() {
    return credentials_ == null ? sirup.service.auth.rpc.proto.CredentialsRpc.getDefaultInstance() : credentials_;
  }
  /**
   * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
   */
  public sirup.service.auth.rpc.proto.CredentialsRpcOrBuilder getCredentialsOrBuilder() {
    return getCredentials();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (credentials_ != null) {
      output.writeMessage(1, getCredentials());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (credentials_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCredentials());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sirup.service.auth.rpc.proto.TokenRequest)) {
      return super.equals(obj);
    }
    sirup.service.auth.rpc.proto.TokenRequest other = (sirup.service.auth.rpc.proto.TokenRequest) obj;

    boolean result = true;
    result = result && (hasCredentials() == other.hasCredentials());
    if (hasCredentials()) {
      result = result && getCredentials()
          .equals(other.getCredentials());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCredentials()) {
      hash = (37 * hash) + CREDENTIALS_FIELD_NUMBER;
      hash = (53 * hash) + getCredentials().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.auth.rpc.proto.TokenRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sirup.service.auth.rpc.proto.TokenRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code auth.proto.TokenRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:auth.proto.TokenRequest)
      sirup.service.auth.rpc.proto.TokenRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_TokenRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_TokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sirup.service.auth.rpc.proto.TokenRequest.class, sirup.service.auth.rpc.proto.TokenRequest.Builder.class);
    }

    // Construct using sirup.service.auth.rpc.proto.TokenRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (credentialsBuilder_ == null) {
        credentials_ = null;
      } else {
        credentials_ = null;
        credentialsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sirup.service.auth.rpc.proto.Auth.internal_static_auth_proto_TokenRequest_descriptor;
    }

    @java.lang.Override
    public sirup.service.auth.rpc.proto.TokenRequest getDefaultInstanceForType() {
      return sirup.service.auth.rpc.proto.TokenRequest.getDefaultInstance();
    }

    @java.lang.Override
    public sirup.service.auth.rpc.proto.TokenRequest build() {
      sirup.service.auth.rpc.proto.TokenRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sirup.service.auth.rpc.proto.TokenRequest buildPartial() {
      sirup.service.auth.rpc.proto.TokenRequest result = new sirup.service.auth.rpc.proto.TokenRequest(this);
      if (credentialsBuilder_ == null) {
        result.credentials_ = credentials_;
      } else {
        result.credentials_ = credentialsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sirup.service.auth.rpc.proto.TokenRequest) {
        return mergeFrom((sirup.service.auth.rpc.proto.TokenRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sirup.service.auth.rpc.proto.TokenRequest other) {
      if (other == sirup.service.auth.rpc.proto.TokenRequest.getDefaultInstance()) return this;
      if (other.hasCredentials()) {
        mergeCredentials(other.getCredentials());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sirup.service.auth.rpc.proto.TokenRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sirup.service.auth.rpc.proto.TokenRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private sirup.service.auth.rpc.proto.CredentialsRpc credentials_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sirup.service.auth.rpc.proto.CredentialsRpc, sirup.service.auth.rpc.proto.CredentialsRpc.Builder, sirup.service.auth.rpc.proto.CredentialsRpcOrBuilder> credentialsBuilder_;
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    public boolean hasCredentials() {
      return credentialsBuilder_ != null || credentials_ != null;
    }
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    public sirup.service.auth.rpc.proto.CredentialsRpc getCredentials() {
      if (credentialsBuilder_ == null) {
        return credentials_ == null ? sirup.service.auth.rpc.proto.CredentialsRpc.getDefaultInstance() : credentials_;
      } else {
        return credentialsBuilder_.getMessage();
      }
    }
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    public Builder setCredentials(sirup.service.auth.rpc.proto.CredentialsRpc value) {
      if (credentialsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        credentials_ = value;
        onChanged();
      } else {
        credentialsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    public Builder setCredentials(
        sirup.service.auth.rpc.proto.CredentialsRpc.Builder builderForValue) {
      if (credentialsBuilder_ == null) {
        credentials_ = builderForValue.build();
        onChanged();
      } else {
        credentialsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    public Builder mergeCredentials(sirup.service.auth.rpc.proto.CredentialsRpc value) {
      if (credentialsBuilder_ == null) {
        if (credentials_ != null) {
          credentials_ =
            sirup.service.auth.rpc.proto.CredentialsRpc.newBuilder(credentials_).mergeFrom(value).buildPartial();
        } else {
          credentials_ = value;
        }
        onChanged();
      } else {
        credentialsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    public Builder clearCredentials() {
      if (credentialsBuilder_ == null) {
        credentials_ = null;
        onChanged();
      } else {
        credentials_ = null;
        credentialsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    public sirup.service.auth.rpc.proto.CredentialsRpc.Builder getCredentialsBuilder() {
      
      onChanged();
      return getCredentialsFieldBuilder().getBuilder();
    }
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    public sirup.service.auth.rpc.proto.CredentialsRpcOrBuilder getCredentialsOrBuilder() {
      if (credentialsBuilder_ != null) {
        return credentialsBuilder_.getMessageOrBuilder();
      } else {
        return credentials_ == null ?
            sirup.service.auth.rpc.proto.CredentialsRpc.getDefaultInstance() : credentials_;
      }
    }
    /**
     * <code>.auth.proto.CredentialsRpc credentials = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sirup.service.auth.rpc.proto.CredentialsRpc, sirup.service.auth.rpc.proto.CredentialsRpc.Builder, sirup.service.auth.rpc.proto.CredentialsRpcOrBuilder> 
        getCredentialsFieldBuilder() {
      if (credentialsBuilder_ == null) {
        credentialsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sirup.service.auth.rpc.proto.CredentialsRpc, sirup.service.auth.rpc.proto.CredentialsRpc.Builder, sirup.service.auth.rpc.proto.CredentialsRpcOrBuilder>(
                getCredentials(),
                getParentForChildren(),
                isClean());
        credentials_ = null;
      }
      return credentialsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:auth.proto.TokenRequest)
  }

  // @@protoc_insertion_point(class_scope:auth.proto.TokenRequest)
  private static final sirup.service.auth.rpc.proto.TokenRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sirup.service.auth.rpc.proto.TokenRequest();
  }

  public static sirup.service.auth.rpc.proto.TokenRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TokenRequest>
      PARSER = new com.google.protobuf.AbstractParser<TokenRequest>() {
    @java.lang.Override
    public TokenRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TokenRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TokenRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TokenRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sirup.service.auth.rpc.proto.TokenRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

