// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_auth.proto

package sirup.service.auth.rpc.proto;

public interface TokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.v2.TokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.auth.v2.CredentialsRpc credentials = 1;</code>
   */
  boolean hasCredentials();
  /**
   * <code>.auth.v2.CredentialsRpc credentials = 1;</code>
   */
  sirup.service.auth.rpc.proto.CredentialsRpc getCredentials();
  /**
   * <code>.auth.v2.CredentialsRpc credentials = 1;</code>
   */
  sirup.service.auth.rpc.proto.CredentialsRpcOrBuilder getCredentialsOrBuilder();
}
